### ISSUE TITLE
automated tests are not working

### ISSUE THREAD

**Issue by wojtek-krysiak** [Arteha/admin-bro-typeorm#6]
I pulled today master and run automated tests `yarn test` and they are not working. There is an error when it comes to storing relation - probably related to this one: https://github.com/Arteha/admin-bro-typeorm/commit/f4958d1f3697f76cb9df710b4b85f17c21ef11b5#diff-10973698552466508fc2a4adcca56622R211

**Comment by Arteha** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/22820043/71485891-c2729400-2813-11ea-8043-b11bf810cb92.png)
