### ISSUE TITLE
Unhandled type: function Boolean() { [native code] }

### ISSUE THREAD

**Issue by lp-bayramali** [Arteha/admin-bro-typeorm#8]
After successful running of the project. Going to admin home page throws

`Unhandled type: function Boolean() { [native code] }`

Also boolean types on admin panel are showing as text-input instead of checkbox. Any of CRUD doesn't work with boolean's.

- admin-bro: ^1.6.0-beta.5,
- admin-bro-expressjs: ^0.4.0,
- admin-bro-typeorm: ^0.1.6-alpha.3,
- typeorm: ^0.2.21,
- typescript: 3.3.3333

**Comment by Arteha** [comment]
Hello.
Fixed in v0.1.6-alpha.4
Thank you.

**Comment by lp-bayramali** [comment]
Thank you :)
